import pandas as pd
import geopandas as gpd

# Load a bixi data file
bixi = pd.read_csv('data/raw/bixi/bixi-2024.csv')

# Retrieve unique start locations and keep first combination of coordinates
bixi_stations = bixi[['STARTSTATIONNAME']].drop_duplicates().rename(columns={'STARTSTATIONNAME': 'STATIONNAME'})
station_coords = bixi.groupby('STARTSTATIONNAME').first()[['STARTSTATIONLATITUDE', 'STARTSTATIONLONGITUDE']].reset_index()
bixi_stations = bixi_stations.merge(station_coords, left_on='STATIONNAME', right_on='STARTSTATIONNAME', how='left').drop(columns='STARTSTATIONNAME').rename(columns={'STARTSTATIONLATITUDE': 'STATIONLATITUDE', 'STARTSTATIONLONGITUDE': 'STATIONLONGITUDE'})

# Create a GeoDataFrame from the bixi stations
gdf_bixi_stations = gpd.GeoDataFrame(
    bixi_stations, 
    geometry=gpd.points_from_xy(bixi_stations['STATIONLONGITUDE'], bixi_stations['STATIONLATITUDE']),
    crs='EPSG:4326'  # Use EPSG:4326 for latitude and longitude coordinates
)

# Filter out invalid geometries
gdf_bixi_stations = gdf_bixi_stations[gdf_bixi_stations.geometry.is_empty == False]

# Filter out invalid points with coordinates (0, 0)
gdf_bixi_stations = gdf_bixi_stations[(gdf_bixi_stations['STATIONLATITUDE'] != 0) & (gdf_bixi_stations['STATIONLONGITUDE'] != 0)]


### Check whether stations are within the city area ###
# Load city area
city_area = gpd.read_file('data/curated/city-area.json')

# Make sure the city area is in the same projection as the bixi stations
city_area = city_area.to_crs('EPSG:4326')

# Create a column that indicates if the station is within the city area
gdf_bixi_stations['WITHIN_CITY_AREA'] = gdf_bixi_stations.within(city_area.geometry.iloc[0])


### Get borough information for each bixi station ###
# Load boroughs data
boroughs = gpd.read_file('data/raw/borough-shapes.json')

# Perform spatial join to find which borough each bixi station is located in
bixi_stations_with_boroughs = gpd.sjoin(gdf_bixi_stations, boroughs[['NOM', 'geometry']], how='left', predicate='within')

# Rename the column to 'BOROUGH'
bixi_stations_with_boroughs = bixi_stations_with_boroughs.rename(columns={'NOM': 'BOROUGH'})

# Drop the index_right column generated by the spatial join
bixi_stations_with_boroughs = bixi_stations_with_boroughs.drop(columns=['index_right'])

# Update the GeoDataFrame with borough information
gdf_bixi_stations = bixi_stations_with_boroughs


# Save the bixi stations to a GeoJSON file
gdf_bixi_stations.to_file('data/curated/bixi-stations.json', driver='GeoJSON')
